/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemywspomaganiadecyzji.frames.decision_tree;

import systemywspomaganiadecyzji.frames.k_means.*;
import Data.Data;
import Data.DecisionTree;
import Data.K_Means;
import Data.ParseDataToMatlab;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author KonradD
 */
public class decisionTreeFrame extends javax.swing.JFrame {

    //private JList columnList;
    JCheckBox[] columns;// = new JComboBox[WIDTH];
    private JPanel columnPanel = new JPanel();

    public decisionTreeFrame() {
        //columnPanel.setLayout(new GridLayout(0, 0, 0, 0));
        columnPanel.setLayout(new GridLayout(0, 1));
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        neighbourCountTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane(columnPanel);
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("buduj drzewo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("ilość klas:");

        jLabel3.setText("metryka:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("wybierz kolumny do grupowania:");

        jLabel4.setText("klasa decyzyjna:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(neighbourCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(neighbourCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*k_nn_method knn = new k_nn_method();
        this.dispose();
        int metric = jComboBox2.getSelectedIndex();
        //System.out.println("zaznaczony element " + jComboBox2.getSelectedIndex());
        System.out.println("zaznaczony element " + metric);
        if(!automaticNeigbourVal){
            //ilosc sasiadow podana przez uzytkownika
            knn.evaluationMode(metric, Data.getInstance().getAllData(), jComboBox1.getSelectedIndex(), Integer.parseInt(neighbourCountTextField.getText()));
        }else{
            //automatyczna ilosc sasiadow od 1 do n-1
            //throw new UnsupportedOperationException("Nie ma");
            knn.automaticEvaluation(metric, Data.getInstance().getAllData(), jComboBox1.getSelectedIndex(), deleteColWithEqualVal);
        }*/        
        int[] columnSelected = new int[columns.length];
        int iterator = 0;
        for (int i = 0; i < columns.length; i++) {
            if (columns[i].isSelected()) {
                //System.out.println("kolumna zaznazcona: " + (i + 1));
                //columnSelectedAL.add(i);
                columnSelected[iterator++] = i;
            }
        }
        columnSelected = Arrays.copyOf(columnSelected, iterator);   
        //K_Means kms = new K_Means();
        //System.err.println(Arrays.toString(columnSelected));
        //System.err.println("odleglosci: " + jComboBox2.getSelectedIndex());
        //kms.group(Data.getInstance().getData(columnSelected), Integer.parseInt(neighbourCountTextField.getText()));
        //kms.group(Data.getInstance().getData(columnSelected), Data.getInstance().getStringColumn(jComboBox3.getSelectedIndex()), Integer.parseInt(neighbourCountTextField.getText()), jComboBox2.getSelectedIndex());
        //ParseDataToMatlab pdtm = new ParseDataToMatlab();
        //pdtm.parse(Data.getInstance().getData(columnSelected));
        //pdtm.compareData(Data.getInstance().getStringColumn(jComboBox3.getSelectedIndex()));
        DecisionTree dt = new DecisionTree();
        dt.generateTree(Data.getInstance().getData(columnSelected), Data.getInstance().getStringColumn(jComboBox3.getSelectedIndex()));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(decisionTreeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(decisionTreeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(decisionTreeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(decisionTreeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new decisionTreeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField neighbourCountTextField;
    // End of variables declaration//GEN-END:variables

    private String[] metrics = {"Euklidesowa", "Manhattan", "Max", "Mahalanobisa"};

    private void fillComboBox() {
        ArrayList<String> headers = Data.getInstance().getHeaders();
        jComboBox2.removeAllItems();
        jComboBox3.removeAllItems();
        for (String s : metrics) {
            jComboBox2.addItem(s);
        }
        //columnPanel = new JPanel();        
        if (headers.isEmpty()) {
            //System.out.println("PUSTO");
            int lp = Data.getInstance().getMaxWidth();
            columns = new JCheckBox[lp];
            for (int i = 0; i < lp; i++) {
                //columns[i].setName(i + " ");
                jComboBox3.addItem((i + 1) + " ");
                columns[i] = new JCheckBox((i + 1) + " ");
                columns[i].setSelected(true);
                columnPanel.add(columns[i]);
            }
        } else {
            columns = new JCheckBox[headers.size()];
            for (int i = 0; i < headers.size(); i++) {
                //columns[i].setName(headers.get(i));
                jComboBox3.addItem(headers.get(i));
                columns[i] = new JCheckBox(headers.get(i));
                columns[i].setSelected(true);
                columnPanel.add(columns[i]);
            }
        }
        columnPanel.revalidate();
        columnPanel.repaint();
        //jScrollPane1.add(columnPanel);
    }
}
