/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eksploracjaDanych;

import systemywspomaganiadecyzji.frames.k_means.*;
import Data.Data;
import Data.K_Means;
import Data.ParseDataToMatlab;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTextField;
import plot.DrawPlot;

/**
 *
 * @author KonradD
 */
public class SeparowalnoscLiniowa extends javax.swing.JFrame {

    //private JList columnList;
    JCheckBox[] columns;// = new JComboBox[WIDTH];
    private JPanel columnPanel = new JPanel();

    public SeparowalnoscLiniowa() {
        //columnPanel.setLayout(new GridLayout(0, 0, 0, 0));
        columnPanel.setLayout(new GridLayout(0, 1));
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane(columnPanel);
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("wybierz kolumny do separowania liniowego :");

        jLabel4.setText("klasa decyzyjna:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("ilosc kolumn " + Data.getInstance().getMaxWidth());
        int[] columnSelected = new int[columns.length - 1];
        int iterator = 0;
        for (int i = 0; i < columns.length; i++) {
            if (columns[i].isSelected()) {
                //System.out.println("kolumna zaznazcona: " + (i + 1));
                //columnSelectedAL.add(i);
                columnSelected[iterator++] = i;
            }
        }
        System.out.println("wybrane kolumny " + Arrays.toString(columnSelected));
        Separate sep = new Separate();
        sep.startSeparate(Data.getInstance().getData(columnSelected), Data.getInstance().getStringColumn(jComboBox3.getSelectedIndex()), true);
        /*Double[] dx = sep.xL.toArray(new Double[sep.xL.size()]);
        Double[] dy = sep.yL.toArray(new Double[sep.xL.size()]);
        double[] d = ArrayUtils.toPrimitive(ds);*/
        DrawPlot.getInstance().draw2D_desc_lines(Data.getInstance().getColumn(0), Data.getInstance().getColumn(1), Data.getInstance().getStringColumn(jComboBox3.getSelectedIndex()), sep.getxL(), sep.getyL());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeparowalnoscLiniowa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeparowalnoscLiniowa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeparowalnoscLiniowa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeparowalnoscLiniowa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeparowalnoscLiniowa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    //private String[] metrics = {"Euklidesowa", "Manhattan", "Max", "Mahalanobisa"};
    private void fillComboBox() {
        ArrayList<String> headers = Data.getInstance().getHeaders();

        jComboBox3.removeAllItems();

        //columnPanel = new JPanel();        
        if (headers.isEmpty()) {
            //System.out.println("PUSTO");
            int lp = Data.getInstance().getMaxWidth();
            columns = new JCheckBox[lp];
            for (int i = 0; i < lp; i++) {
                //columns[i].setName(i + " ");
                jComboBox3.addItem((i + 1) + " ");
                columns[i] = new JCheckBox((i + 1) + " ");
                columns[i].setSelected(true);
                columnPanel.add(columns[i]);
            }
        } else {
            columns = new JCheckBox[headers.size()];
            for (int i = 0; i < headers.size(); i++) {
                //columns[i].setName(headers.get(i));
                jComboBox3.addItem(headers.get(i));
                columns[i] = new JCheckBox(headers.get(i));
                columns[i].setSelected(true);
                columnPanel.add(columns[i]);
            }
        }
        columnPanel.revalidate();
        columnPanel.repaint();
        //jScrollPane1.add(columnPanel);
    }
}
